spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripchoice?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: 1234
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
#        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false

# [개발용] 실제 서비스 시에는 .env 또는 secret 프로필에 등록해서 사용
jwt:
  issuer: tripchoice
  secret: tCfj2cTfEvyAYeA+vJKihHb7t3Tt0NQZeJnvFkPbKtU=
  expiry-seconds: 3600
  refresh-expiry-seconds: 259200

#server:
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: localhost
